name: Unzip zip file and push contents

on:
  push:
    paths:
      - '*.zip'

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Unzip file
        run: |
          unzip -o index.zip -d ./unzipped

      - name: Commit unzipped files
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add unzipped
          git commit -m "Auto-unzipped index.zip"
          git push
